### PR TITLE
add list of used colors in layout

### LINKED ISSUE #54: Offer a list of colors currently used on the layout
issue migrated from [https://github.com/JcBernack/anno-designer/issues/16](https://github.com/JcBernack/anno-designer/issues/16)

- Display colors as filled rectangles?
- Display colors as raw values? ARGB or HEX or both?
- Display list of colors in statistics view?
I think best would be to wait till PR #23 is merged.
- Display list of colors on exported image?
- List of colors in current layout available via color picker?

### PR DESCRIPTION
**Pull request by FroggieFrog**
This should fix #54.

I added an expander with a list of colors used in the current layout. The style and size of the color rectangles matches the rectangles from the color picker.

When the user double clicks on a color, then the color is selected in the color picker. From there the user can use the feature to apply the color to the current selection.
There are also ToolTips for the user.

Anno_Designer_colors_in_layout

### CODE REVIEW

**Comment by AgmasGold** [comment]
This implementation of this feature looks very nice, it's some great code.

The one thing that I'd possibly like to see is for it to wrap by default, rather than increasing the width of the dock-panel (like how the treeview currently works - it just adds a scrollbar instead of increasing width).

**Comment by FroggieFrog** [comment]
I will test it tomorrow. Maybe there needs to be a fixed MaxWidth or so for the WrapPanel to work.

**Comment by AgmasGold** [comment]
Yeah - for the tree view I just bound the width with a one way databind from the width of the buildings panel.

**Comment by FroggieFrog** [comment]
The expander now has a MaxWidth and all colors are wrapped to a new row.
I think adding a scrollbar is unnecessary, because there are typically not that many colors in a layout.

- before:
before

- after:
after

**Comment by StingMcRay** [comment]
Very nice job :)

**Pull request merged**
