### PR TITLE
added translations for road tiles

### PR DESCRIPTION
**Pull request by FroggieFrog**
- merged current master
- added translations for road tiles
- use Dictionary.TryGetValue

### CODE REVIEW

**Comment by StingMcRay** [comment]
Do you want me to place the Road Translatin into the treeLocalizations ?
(as they are appear on the sheet)

**Comment by FroggieFrog** [comment]
I added them in the Excel sheet and in code. So where do you want them to add?

I added them in this branch because it felt right to do so.

**Comment by StingMcRay** [comment]
Put your code into the Translation-Preset-Tree on our branch
Thanks for the .TryGetValue command, did not think abt that.

**Comment by FroggieFrog** [comment]
Ok, I thought this was a PR for the branch "Translation-Preset-Tree". Glad to help.

**Comment by StingMcRay** [comment]
:) nor worries :)
It was there for testing the try/catch method, because it slow down the preset tree on switch Languages on my computer so... (was a bad thing on my PC that slow down all processing) 
Anyway its still for test available but as long all handlers are right written the 'try' will alway's succeeding

**Pull request merged**
