### PR TITLE
separate statistics view (better performance)

### LINKED ISSUE #16: move statistics from canvas
I think it is better to move the statistics out of the canvas and display them on a separate panel beside the canvas.
The text for the statistics don't change at every frame and so there is no need to paint them on every frame.

Maybe a separate DockPanel like the other one. this Dockpanel could contain many TextBlocks in some GroupBoxes.
This should improve performance when simply moving the mouse.

### PR DESCRIPTION
**Pull request by FroggieFrog**
I seperated the statistics view from the canvas to achieve a better performance.
This should fix #16.

Things to note:
1. I tried to "migrate" the export to image logic, but it was a lot harder (for me) than I thought. Please feel free to adjust it.
2. I added some new translations. Please add those values to the excel sheet.

> eng
> { "StatTiles" , "Tiles"},
> { "StatNameNotFound" , "Building name not found"},
> 
> ger
> { "StatTiles" , "Kacheln"},
> { "StatNameNotFound" , "Gebäudename nicht gefunden"},
> 
> pol
> { "StatTiles" , "Płytki"},
> { "StatNameNotFound" , "Nie znaleziono nazwy budynku"},
> 
> rus
> { "StatTiles" , "Плитка"},
> { "StatNameNotFound" , "Название здания не найдено"},

### CODE REVIEW

**Comment by AgmasGold** [comment]
I've just been looking through the code (not started testing yet), and from what I can see it looks alright. I have noticed 2 things it particular (from a code style point of view):

* PrivateMethods should be PascalCase, not camelCase (which some of your private methods are)
* Events represent that something has happened, and should be named as such - `UpdateStatistics` sounds like a method you would call, not an event. I think `StatisticsUpdated` might be a better fit?

Thanks for the .editorconfig file by the way. I did not know about it - it looks like a very useful feature.

**Comment by FroggieFrog** [comment]
editorconfig:
[Sample from roslyn project](https://github.com/dotnet/roslyn/blob/master/.editorconfig)

naming convention:
I just used the quick fix of Visual Studio:
IDE1006

async render to file:
This is just the copied comment of the old method from annocanvas. Who reads comments? 😁

I will adjust the comment, the naming of private methods and the name of the event.

**Comment by AgmasGold** [comment]
My visual studio is set differently - and the rest of the project uses PascalCase for private methods - maybe we should edit that in the .editorconfig for this project.

**Comment by AgmasGold** [comment]
It looks very nice and smooth, and I like the grouping. It might be nice to add a slight margin so the edges of the grouping are not quite so close the separators.

**Comment by FroggieFrog** [comment]
I tried to fix the editorconfig file and the naming convention.
Also update statistics on delete key and adedd padding to the groupboxes.

**Comment by AgmasGold** [comment]
It looks like there are some inconsistencies between how this pull request exports images from the canvas and what it looks like currently from master.

The main thing is that the when rendering at extremes it cuts off parts of the canvas, or renders the entire 
canvas including all the empty space. All below images were exported with the use current zoom level option turned off, apart from the last 2.

It looks like the use current zoom level option never worked in the first place.

I haven't looked into the export code yet, so I am not sure what could be the issue, but I think it's a better idea if the default behaviour is to have it export at the minium zoom level (the current behaviour on master).

The stats window background is also no longer transparent, which doesn't show on the images below - but I prefer this and thats not the main issue.

### Images
<details>
<summary>Click to expand exported images</summary>

* Default zoom levels + stats (master | this code)
master
frog
* Default zoom levels without stats (master | this code)
masterns
frogns
* Max zoom with stats (master | this code)
masterzoom
frogzoom
* Max zoom without stats (master | this code)
masternszoom
frognszoom
* Max zoom with stats and use current zoom selected
usecurrent
frogusecurrent

**Comment by FroggieFrog** [comment]
The backgroundof the statistics view is transparent again.

As I said the logic of exporting to file is a little bit above my current knowledge. Feel free to adjust.

**Comment by FroggieFrog** [comment]
I played around a little bit and I think there is a solution.
There has to be a container control which contains the canvas and the statistics view.
Then on export we can (like the old logic) create a new container control with new canvas and statistics view. Set all properties on the new controls and ad them to the new container control.
This new container control is then used for export.

Does anyone have another/better solution?

**Comment by FroggieFrog** [comment]
I implemented a container control (really quick and dirty) and the export of just the AnnoCanvas works fine.
But to export the statistics I have trouble to calculate the size.

So please feel free to help 😄

**Comment by AgmasGold** [comment]
Sorry for the slow reply,

This message has been copied to the pull request.

I've been messing and trying to get your code to export correctly - I fixed the size, but the contents were always empty (the data-bound TextBlocks). Ideally I want to build on your code, but I tried many different things including solutions from [here](https://stackoverflow.com/questions/14057763/saving-frameworkelement-with-its-datacontext-to-image-file-does-no-succeed).

As it happens, I had a different approach that I was trying the day before you committed your attempt, which did function correctly. It just adds a Grid element to the AnnoCanvas, which I can then populate with the StatisticsView when exporting if required.

**Currently the issue I am seeing is that the group box borders are not being masked by the text correctly.**
<details>
<summary>Show exports</summary>

teststats
test
</details>

There should be a pull request to merge my older solution into your code. The only drawback is that we loose transparency on the statistics, but I don't think this is a major issue, and as I mentioned above.

**Comment by AgmasGold** [comment]
I still need to do a quick check over the code, but things look good so far. I did find one issue (with my code, actually). The stats view (that I add to the canvas when exporting) doesn't scale it's text while the rest of the canvas does scale. This means you end up with situations like this:
<details>
<summary>Show images</summary>

image
* Zoomed in: 
teststat

Zoomed out:
test
</details>

I really want to merge this change, and I am happy to allow this and fix this inconsistency at a later date, I will try and see what I can do - I can definitely remove the scrollbar at least. Do you have any ideas to deal with this? Obviously, it might be the case that even if the text scaled down, it still wouldn't fit.

**Comment by AgmasGold** [comment]
We should make a decision on this - I am not sure how to fix the the scaling issue I mentioned above, and this change is a blocker to others, is there anything you wish to try @FroggieFrog or @StingMcRay, or should we merge this change?

**Comment by StingMcRay** [comment]
I will test this branch code later tomorrow then you will hear, but as fare i have already seen is was a fine peace and no issues seen (for the eye)

**Comment by AgmasGold** [comment]
Check my commment above, you can see the issue with scaling based on if the user exports when zoomed out or zoomed in.

**Comment by FroggieFrog** [comment]
I'm also in the process of testing ...

**Comment by FroggieFrog** [comment]
I can not reproduce any distortions.
So I can't see any issues with this PR. :shipit: 

Workflow:
1. Open "02.ad"
2. Export image (normal_zoom)
3. Scroll mouse wheel to zoom out so the entire layout is visible
4. Export image (complete_zoom_out)
5. Scroll mouse wheel to zoom in so only a red square is visible
6. Export image (complete_zoom_in)

I did this on 2 machines.
1. Win 10 1809, 1920*1080, scaled to 100%
2. Win 10 1809, 3840*2160, scaled to 250%

Testfile: 
[02.zip](https://github.com/AgmasGold/anno-designer/files/3155875/02.zip)

(I can't get the expander to work..)
-  FullHD - normal
02_normal_zoom
- FullHD - zoom out
02_complete_zoom_out
- FullHD - zoom in
02_complete_zoom_in

- HighDPI - normal
02_highdpi_normal_zoom
- HighDPI - zoom out
02_highdpi_complete_zoom_out
- HighDPI - zoom in
02_highdpi_complete_zoom_in

**Comment by StingMcRay** [comment]
As Fare i see its nice : Stats text are scaled on, but i have 1 NOTE : 
I see that the 1 Grid line between most right Obj and Stats Window is also colored white (nice touch btw) but ca that be undone?
Example : This 
afbeelding
Will on export end as this 
afbeelding

Question : Can the stats scaled in a way that all text is in the exported img ?
afbeelding

**Comment by FroggieFrog** [comment]
The white line at the right is the margin of the statistics view.
I djusted it and got the output below.

I also tried to calculate the height, but my knowledge of the layouter of WPF is somewhat limited. My attempts are comments in the code.

Testfile: [03.zip](https://github.com/AgmasGold/anno-designer/files/3156478/03.zip)
- export before
before
- export after
after

**Comment by StingMcRay** [comment]
Thats nice :) 
Abt the try's i will look ad that tomorrow (Or Agmas will pick this up)

**Comment by StingMcRay** [comment]
NOTICE : 
When testing the Exporting of the 'Render selection highlights on exported image' i discovered an issue: 
Selecting in program : 
afbeelding
On exported image
afbeelding

As you can see the selected objects are on export outside the objects. I also tested it on the 8.2 and there it was as normal : 
afbeelding

As this issue i discovered on this tests, i just report them here

**Comment by StingMcRay** [comment]
I discovered an issue, but i will test again, has to do wih Export Image and Zoom + Render Selection

**Comment by FroggieFrog** [comment]
Heureka!
I think I got it:

- export without selection
02_after
- export with selection
02_after_with_selection

**Comment by FroggieFrog** [comment]
Are there any issues left with this PR?

**Comment by AgmasGold** [comment]
Yep, looks good. I was just waiting an extra day just in case :)

**Comment by FroggieFrog** [comment]
Am I missing something or was just closed without a merge?

**Comment by AgmasGold** [comment]
Erm- sorry!! Must havew clicked the wrong button, whoops

**Comment by AgmasGold** [comment]
I meant to merge this one first before I merged the other requests.....

**Comment by FroggieFrog** [comment]
I try to fix the conflicts tomorrow.

**Comment by FroggieFrog** [comment]
@AgmasGold 
🚢 🚀

**Pull request merged**
