### PR TITLE
add export to fandom wiki template (Anno 1800)

### PR DESCRIPTION
**Pull request by FroggieFrog**
I saw this as a possible feature in the projects.

Currently this is hard coded (because it is faster to develop). And also because at the moment I have no idea how a template system could look like.

There has to be a mapping between the identifiers in `presets.json` and the names/icons used in the wiki. Therefore I added the `fandomNameMapping.json`. This could be updated independently from the main application like the other presets. (also auto update could be added)

To test and verify it I used the following layout based on the corresponding layout in the wiki. The zip file also contains the export from this PR.
[Schnapps_02_WH.zip](https://github.com/AgmasGold/anno-designer/files/3191585/Schnapps_02_WH.zip)

**What do you think? Is this a sensible way to go?**

Things like dialog for save location, localization, maybe better menu structure could be added later if this export logic is sensible.

### CODE REVIEW

**Comment by StingMcRay** [comment]
The icons (files) of wiki start without the ` An_ ` numbering system (like A7_<iconname>), this i build in on the Anno designer to keep different Anno icons separated. Also they all staring with a Capital
Check here : https://anno1800.fandom.com/wiki/Icons

**Comment by StingMcRay** [comment]
For the Wiki Export there are several things that need to be filled in manually : 
- Icon Name that is used for the title *without .png*
- Name of the layout
- Layout image (this is the image that is exported from the AD)
- Layout Description text

Further more:
the owner likes to have the ordering as stand on https://anno1800.fandom.com/wiki/Template:Production_layout don'tknow of that is possible

And thanks to start on this, but the request of @AgmasGold yesterday was to make this app separated from the AD Code 
*yeah we discus things sometimes on Discord, maybe handy to run it if you able too :)*

**Comment by FroggieFrog** [comment]
_Discord is not possible at the moment_

**So this should be created as a separate application where you load the layout (*.ad file) and can create a template for the wiki?**

If this should be a separate application than this application needs to do some calculations that are already done in the main application. Also all presets have to be loaded again.
A compromise could be to add the export(s) as separate libraries (*.dll files). So kind of a plugin/add on system.
Having it all in the same application would make things easier and because of separate libraries there would be a (kind of) clear architecture.
Also why should a user start different applications? Have the user click a button, fill some fileds and there is a new folder/new zip file with the exported image and the prefilled wiki template.

Since there are not all for the wiki needed values in the presets my opinion of the exported template was more of a starting point for the user.
Currently the user has to type evrything by hand for the template. With this PR there are already some values in the template and the user has to fill in less values by hand.

The mapping between identifiers and names in the wiki is somewhat weird.
The [documentation](https://anno1800.fandom.com/wiki/Template:Production_layout/doc) says:
> You should only insert the building's icon's name, without anything else.

And the corresponding icon filename for the fire station is `Fire_station.png` (with underscore) but the layout `Schnapps 04 WH FS` uses `Building 5 Type = fire station` (no underscore).
The wikitext of the [icons page](https://anno1800.fandom.com/wiki/Icons) is
`Fire_station.png|Fire Station`
So it seems underscores and casing do not matter.

**Comment by StingMcRay** [comment]
As fare the separation : we only need the .ad file (icon names are there too). Preset do not be required, as <maybe> we can get the costs (like building need, workforces and maintain costs) get from the wiki it self by reading the building information *that was my plan anyway, don't know of that is possible*
that i was planning to look ad next week :)

For the icon names, the Anno 1800  Wiki Owner let me know though discord the following : 

> banan1996.1996
> Ah, and when it comes to icons names, you can use the same names as in AD. On wiki we would just have to create redirect pages to actual icons uploaded to wiki

so then you know :)

**Comment by AgmasGold** [comment]
The main reason I want to keep this separate is that this in an 1800 **wiki** specific feature, whereas Anno Designer is for versions of Anno. Ideally I want to keep Anno Designer as fit for purpose for all Anno's as possible, and adding version specific features will slowly dilute this. Obviously, for some features, there is no way around this.

Implementing it as some kind of plugin would be a nice idea. I realise it would require some code rewriting so that we don't have duplicated logic.

**Comment by FroggieFrog** [comment]
I get your point(s).
Will check how to make it somewhat separate from the main application. 

Maybe extract some logic to extra libraries.

**Comment by StingMcRay** [comment]
I have spoken with Banan today, about some issues for the template: 
the following things are changed in the template : 
There are now up to 15 types of buildings: `Building 1 Type =` and `Building 1 Amount =`
and also up to 8 types of production type: `Production 1 per minute =` and `Production 1 type =`

**Comment by StingMcRay** [comment]
Tested the application `FandomTemplateExporter.exe`
this is the output from my `Metal Weapons Sawing Machines.ad`
Metal Weapons Sawing Machines

this is the result: 
{{Production layout
|Icon = 
|Name of the layout = Metal Weapons Sawing Machines
|Layout image = 
|Building 1 Type = Wood
|Building 1 Amount = 1
|Building 2 Type = Sewing machines
|Building 2 Amount = 2
|Building 3 Type = Warehouse
|Building 3 Amount = 2
|Building 4 Type = Steel beams
|Building 4 Amount = 2
|Building 5 Type = Charcoal kiln
|Building 5 Amount = 2
|Building 6 Type = Weapons
|Building 6 Amount = 3
|Building 7 Type = Fire station
|Building 7 Amount = 3
|Building 8 Type = Steel
|Building 8 Amount = 3
|Layout description = 
|Size = 31 x 43
|Tiles = 1333
|Author = 
|Source = 
|Production 1 type = Sewing_machines
|Production 1 per minute = 4
|Production 2 type = Weapons
|Production 2 per minute = 2
|Production 3 type = Steel_beams
|Production 3 per minute = 2,67
|Production 4 type = Coal
|Production 4 per minute = 4
|Production 5 type = Steel
|Production 5 per minute = 6
|Credits = 33200
|Timber = 104
|Bricks = 95
|Steel beams = 40
|Windows = 16
|Reinforced concrete = 
|Balance = -2315
|Farmers workforce = -5
|Workers workforce = -870
|Artisans workforce = -300
|Engineers workforce = 
|Jornaleros workforce = 
|Obreros workforce = 
|Influence = 
|Attractiveness = -60
}}

So end-user has only a few things to fill in (and or removed)
*test is Ok and this PR can be merged*

**Comment by FroggieFrog** [comment]
After consultation with @AgmasGold I merge this PR.

**Pull request merged**
