### PR TITLE
add basic build script

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR adds a basic build script using [cake](https://cakebuild.net/).
Hopefully this makes it a little easier to create a new release with the correct files.

To make life easier there is a `StartCakeBuild.bat` where you can enter `1` or `2` for a Debug or Release build.
When choosing to build a Release build then there will be a `Anno.Designer.vXX.zip` file in the `build\out` directory.
The build scripts creates log files for MSBuild in the `build\logs` directory. These files can be best viewed with [MSBuildStructuredLog](https://github.com/KirillOsenkov/MSBuildStructuredLog).

The script adjusts the version number in the `AssemblyInfo.cs` files according to the `version.txt` file.

**So for a new release you need to do the following:**
1. adjust version in `version.txt`
2. adjust version in `AnnoDesigner\Constants.cs`
3. start `StartCakeBuild.bat` and choose `2`

**Things that could be made easier in the future:**
- simpler way of versioning (I tried to be minimal invasive 😄)
- generic way of copying the needed files for the application (currently hard coded dependencies)

### CODE REVIEW

**Comment by AgmasGold** [comment]
I can't seem to get this to work - "MSBuild cannot find the executable", fails at task "Build".

Running it from `./build/StartCakeBuild.bat`, the path to the exe is `./AnnoDesigner/bin/{Config}/AnnoDesigner.exe`.

If the bat file needs to be run from somewhere other than the `./build` folder, it's probably worth documenting somewhere - maybe a message at the start of the .bat file, to begin with?

**Comment by FroggieFrog** [comment]
Have you checked the log in `build\logs`?
The script "build.cake" uses MSBuild from VS2017 (line 115).

I will check it tomorrow anyway.

**Comment by AgmasGold** [comment]
log folders are empty

**Comment by AgmasGold** [comment]
I am using VS 2019 (and don't have VS 2017 installed), could that be it?

**Comment by FroggieFrog** [comment]
Yes that is possible.
Change line 115 to VS2019 and it should work. 

I will check if there is a way to find it automatically.

**Comment by FroggieFrog** [comment]
Took me a while to realize there is a (known and fixed in future update) bug in cake.
Now you have to enter which version of MSBuild to use.
Can be adjusted when cake 0.34 is released.

**Comment by AgmasGold** [comment]
Nice, thanks for this - unfortunately, it still doesn't work for me. Log folders are empty, but I do have an error in the cmd window:

`MSBUILD : error MSB1008: Only one project can be specified.`

**Comment by FroggieFrog** [comment]
Could please add `-Verbosity Diagnostic` at line 56 in `build/StartCakeBuild.bat` to enable diagnostic mode of cake?
Then watch out for a line beginning with`Executing: "C:/Program Files (x86)/Microsoft Visual Studio/...MSBuild.exe"` and copy it here.
I think it could be an issue with a path containing spaces. This would be a bug in cake which I could report.

**Pull request merged**
