### PR TITLE
add predefined colors

### PR DESCRIPTION
**Pull request by FroggieFrog**
This is a fix for issue #37.

You can define a color for each `Template` from the `presets.json`.
If you want to be more specific then you can add another definition which contains the `Template` and the specific `Identifier`.

Example:
```json
{
    "TargetTemplate": "Farmfield",
    "TargetIdentifiers": [],
    "Color": {
        "A": 255,
        "R": 255,
        "G": 165,
        "B": 0
        }
},
{
    "TargetTemplate": "Farmfield",
    "TargetIdentifiers": [ "Agriculture_06_field (Sheepfold)" ],
    "Color": {
        "A": 255,
        "R": 60,
        "G": 179,
        "B": 113
        }
}
```

This would use the color `DarkOrange` for all farm fields (e.g. potato fileds) and use the color `MediumSeaGreen` for the Sheepfold.

The user can adjust the colors of all objects in the selection to the predefined color using the previuosly and now active SplitButton.
If an old layout is loaded and a object has no template saved in the layout then the app tries to find the template from the current presets using the identifier.

The general structure is capavle of using multiple ColorSchemes (Different ColorScheme for different games?).
But at the moment there is only one ColorScheme used ("Default").

To make the developers life easier there is a ColorPresetsDesigner available (see PR #84).

### CODE REVIEW

**Comment by StingMcRay** [comment]
looks promising  : nice touch on identifiers there :)

**Comment by StingMcRay** [comment]
I have one question : 
Is it still possible to change colors while a preset color is set ?
*i tested today but its seams that is not possible yet*

**Comment by FroggieFrog** [comment]
Yeah this is totally possible.
I can't reproduce your issue:
predef_colors

**Comment by StingMcRay** [comment]
You are right, i was selecting the building again on the list instead of push 'place building'
what i did was selecting a building from the preset list, and then change color, and then selecting the same building again (shame on me)

**Pull request merged**
