### PR TITLE
add ColorPresetsDesigner (depends on PR #83)

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR adds a designer for the `colors.json` and depends on merge of PR #83.

It is intended as a developer tool only to make it easier to define predefined colors.
It is a seperate application but depends on a compiled version of AnnoDesigner. This should not be an issue for developers 😄

Color_Presets_Designer_1 0 0 0

**Features:**
- add/delete ColorSchemes
- add/delete/copy PredefinedColors
- add/remove Identifiers to PredefinedColors
- change version of `colors.json`
- create backup of `colors.json` on save
- only allow TemplateNames from `presets.json`
- only allow Identifiers from `presets.json`

Hopefully this makes the life of the developers easier 🍨

### CODE REVIEW

**Comment by StingMcRay** [comment]
🥇 
Niceeee :)

**Comment by StingMcRay** [comment]
As i tested this program today i noticed when try to clean the preset color list (Template tab) the program 'errored off' without any message and close the program

**Comment by FroggieFrog** [comment]
Yeah, it is a developer tool, so no error handling :-)
I will add some basic error handling.

**Comment by StingMcRay** [comment]
I know :) but just want to report, because even it is a 'developer' program, ppl can alway's download source :)

**Comment by FroggieFrog** [comment]
I just fixed those NullRefs and added an exception log for unhandled exceptions.
Also there will be an application log (application_log.txt) using the `TextWriterTraceListener`.

If loading the data yields errors (e.g. wrong selected file) then there will be a message to the user and no crash.
Hopefully this should do it for now 😁

**Comment by StingMcRay** [comment]
The following question is only if you want this too, and if you have time : 
Can you link the search list of the identifiers to the selected Template name ? (to shorten the search list)

**Comment by FroggieFrog** [comment]
As you wish my master. (completed)

**I found another issue: road tiles.**
Those are not in the presets.json.

So I think there are different possibilies:
1. Ignore it.
Just add those entries by hand in the colors.json.
2. Add road tile to the presets.json.
This is somewhat complex because the presets parser and the main application must change.
3. Add template and identifier by code.
This would at "Road" to the TemplateName and Identifier lists.
Incorrect combinations are available.
Need to change code when the Identifier changes. (e.g. add seperate entries for dirt road and paved road)

But after all I think this should be another issue after this is merged/available.

**Comment by StingMcRay** [comment]
I think for the road tile we will find a way indeed when this project is merged into our master :)
When is, i will look into that as first, to get the road a gray (paved and stone roads) or sand color for all dirt roads

**Comment by StingMcRay** [comment]
Tested the Identifier Search list : 
Thanks for the changes, makes our lives more easier :)

**Pull request merged**
