### PR TITLE
auto update for presets

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR adds the functionality of auto checking and downloading new versions of the presets file.
The main component used to do this is [Octokit](https://www.nuget.org/packages/Octokit).

So if you stick to the pattern for tagging the releases ("Presetsv*") this PR checks the version numbers and asks the user if it should be downloaded.
If you user says yes then the new presets file will be downloaded to the app directory (with a temporary file name) and the app will be restarted.
On start the app checks if there is a temporary file and replaces the presets file with its content.

Maybe in the future this could be expanded to update the entire app or parts of it (color presets, icon mapping etc.).

**Things to be aware of:**
1. This uses the GitHub API and this API has a [rate limit](https://developer.github.com/v3/#rate-limiting). Currently this at 60 requests per hour per IP address.
If the limit is hit then simply there is no check. This should not hurt any user. In the worst case their last check for a new presets file is older than 1 hour.
2. Currently there is only support for downloading a single asset file.
If there is a release which contains `presets.json` and `icons.json` as an asset then only one is found/downloaded.

**TODOs**
- [x] translation
- [x] (more) error handling
Especially dealing with write access or the lack of it.
- [x] support updates which include icons (`Presets.and.Icons.Update*.zip` file)
- [x] support for updates to `icons.json`
Currently there is no version info in the file. Workaround could be a `LastWriteTimeUTC` of local file and publish date of release.
All new generated `icons.json` files will have a version info and the app can also load the "old" files. So this todo should be fixed.
- [x] \(optional) support for updates to `colors.json`
Currently there is no version info in the file. Workaround could be a `LastWriteTimeUTC` of local file and publish date of release.
As there is currently no support for predefined colors this todo is optional.
- [ ] \(optional) support for creating/restoring a backup of the complete application

Is it acceptable for this project to use NuGet and more dependencies?

### CODE REVIEW

**Comment by FroggieFrog** [comment]
I think the main reason for this PR is complete.
**The prerequisites for an auto update of presets are:**
1. releases are tagged with `Presetsv*` (replace * with version number)
2. asset containing `presets.json` and `icons` folder must start with `Presets.and.Icons.Update` and be a zip file
3. to check for a new version the version found in local `presets.json` is used

**Comment by AgmasGold** [comment]
I haven't properly looked at the code, but is there a setting to the user can enable/disable this feature?

**Comment by AgmasGold** [comment]
Oh - and on the point of nuget packages - I am all for them - nuget away! Does Xceed have a nuget package?

**Comment by FroggieFrog** [comment]
Yes, Xceed has NuGet. I will convert to it with this PR.
>is there a setting so the user can enable/disable this feature?

The check uses the same toggle as `EnableAutomaticUpdateCheck`.

**Comment by AgmasGold** [comment]
Just been looking through the code, this looks great by the way.

3 things I think might be worth editing:
* Suffixing async methods with `Async` - e.g `DownloadNewPresetsAsync()`
* Writing the error log when an error occurs - `App.LogErrorMessage(Exception ex)` - This will be useful for debug in future.
* Finally, the method that checks for admin permissions - surely the user will just get stuck in a loop of the app restarting? E.g - They can't write to the folder, so the app shows them an error message, then the app restarts, checks for updates, they can't write to the folder, app shows error message, app restarts etc...

Also in my tests, I set up a user account with no write permissions to the folder - the presets.json did not update, but I got no error messages from the application, and it looks like the _webClient.DownloadStringAsync() actually completed successfully, as the StatusMessage on the MainWindow was "Version up to date."

**Comment by FroggieFrog** [comment]
1. I added the Async suffix.
2. Relevant errors are written to the error log.
In my opinion there are some not so relevant errors for the user to show a message. Maybe it would be useful to add a better logging mechanism (like [NLog](https://nlog-project.org/)).
3. You are right. I just forgot to add it. It should be fixed now.
If you have no write access to the folder then there would also be an error when writing to the error log 😎 Another point for a logging mechanism.
4. I added the Extended Wpf Toolkit as a NuGet package.
Maybe there is a little more work to do when packaging a new release. Maybe a kind of build script would help there out (like [Cake](https://cakebuild.net/)).
5. This PR only checks for updates to the presets. The check for a new version is left untouched. Hence the message in the status bar.
As I said this update logic could later be extended to update the complete application. But this is more complicated because of files already in use etc.
There are some tools/frameworks for updates like that (e.g. [Squirrel](https://github.com/Squirrel/Squirrel.Windows)).

To test this PR you could simply edit your local `presets.json` and change the version info to e.g. `2.0.1`.

**Comment by AgmasGold** [comment]
The things you mention about NLog, Squirrel, and Cake look very interesting. I've not used any of them myself, but I can see that it could be useful to move to them.

It looks like Squirrel might no longer be maintained?

**Comment by AgmasGold** [comment]
resolved the conflicts in csproj, merging this PR

**Pull request merged**
