### PR TITLE
- adjusted layout of about view

### PR DESCRIPTION
**Pull request by FroggieFrog**
- adjusted mesage when de-/register file extesion
- adjusted some translations

### CODE REVIEW

**Comment by FroggieFrog** [comment]
This should fix #10

**Comment by AgmasGold** [comment]
Hi @FroggieFrog,

Before I can accept this pull request, can you please mirror the changes and tweaks you made to the Translations dictionary to the spreadsheet that holds all the translations. [https://docs.google.com/spreadsheets/d/1CjECty43mkkm1waO4yhQl1rzZ-ZltrBgj00aq-WJX4w/edit#gid=0](https://docs.google.com/spreadsheets/d/1CjECty43mkkm1waO4yhQl1rzZ-ZltrBgj00aq-WJX4w/edit#gid=0)

**Comment by FroggieFrog** [comment]
I added all new and changed translations.
Despite adding default values for polish and russian in the Localization.cs I left them out of the sheet.
[Anno Designer Translations.xlsx](https://github.com/AgmasGold/anno-designer/files/3116563/Anno.Designer.Translations.xlsx)

**Comment by AgmasGold** [comment]
Is it possible you could add these directly to the google sheet? Also - leave out the default values - the macro I have set up on the google sheet to generate the code automatically fills in the english value if the cell is empty. 

It would be better if you could fill those language translations in, I recommend using DeepL to get the other language translations.

**Comment by FroggieFrog** [comment]
For editing the sheet directly I need a google account. I need one fitst, so I edited it offline.
I did not know abot the macro and that this class is autogenerated. It would be better to document this somewhere.

If you insist than I will creat a google account and edit the sheet directly and fill in autotranslated values.

**Comment by AgmasGold** [comment]
Alright, no worries - I don't want to force anyone to make a google account if they don't have one. I'll add the changes in myself, then merge the pull request. 
It is documented in a comment at the start of the dictionary:
image

I wasn't going to write all that out by hand 😄 !

**Comment by FroggieFrog** [comment]
Sorry, I did not saw this comment. A classic :-)

**Pull request merged**
